server:
  port: 8000
spring:
  config:
    import:
      - classpath:gateway.yml
      - classpath:satoken.yml
  application:
    name: chenyun-gateway
  data:
    redis:
      host: 192.168.116.131
      port: 6379
      password: 123456
      database: 0
      connect-timeout: 10000ms
      lettuce:
        pool:
          min-idle: 50
          max-idle: 500
          max-wait: 3000ms
          max-active: 1000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.116.131:8848
        username: nacos
        password: nacos
        enabled: true
    inetutils:
      timeout-seconds: 5
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://127.0.0.1:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
logging:
  config: classpath:log4j2.xml
